### ISSUE TITLE
Errores detectados

### ISSUE THREAD

**Issue by lmbanegas** [melisabernalvilla/mercado-liebre_digital#5]
Home: 

- Boxshadow solo debe verse al pasar el mouse por encima del producto. 
- Footer: 1) El background debe ser blanco. 2) Los iconos deben cambiar de color al pasar el mouse por encima del mismo.

Login:
- Footer: Los iconos y texto de tarjeta, envio y seguridad no están alineados en tamaño de pantalla desktop
- Boton enviar no cambia al color #0022AA al pasar el mouse por encima.

Register: 
- Footer: Los iconos y texto de tarjeta, envio y seguridad no están alineados desde 361px a 615px

**Comment by melisabernalvilla** [comment]
corregido
